name: Server

on:
  push:
    branches: [main]
    paths:
      - "server/**"

  workflow_dispatch:

defaults:
  run:
    working-directory: ./server

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn build

      - name: Copy dist to production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "server,!server/node_modules,!server/ormconfig.js"
          target: "~/app/gorestaurant/"

      - name: Install dependencies on production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/gorestaurant/server
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart gorestaurant-api
